use_frameworks!

platform :ios, '8.0'

target 'ProatomicOpenSubclasses_Example' do
  pod 'ProatomicOpenSubclasses', :path => '../'

  target 'ProatomicOpenSubclasses_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase'
  end
end
